### ISSUE TITLE
Version installed from pip did not install logbook

### ISSUE THREAD

**Issue by goodevilgenius** [hongquan/CurliPie#2]
I installed `curlipie` with `pip3 install --user curlipie`, then tried the following:

```python
from curlipie import curl_to_httpie
```

Then, got the error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/drj/.local/lib/python3.8/site-packages/curlipie/__init__.py", line 5, in <module>
    from .pie import curl_to_httpie, ConversionResult   # NOQA
  File "/home/drj/.local/lib/python3.8/site-packages/curlipie/pie.py", line 12, in <module>
    from .curly import CURLArgumentParser
  File "/home/drj/.local/lib/python3.8/site-packages/curlipie/curly.py", line 11, in <module>
    from logbook import Logger
ModuleNotFoundError: No module named 'logbook'
```

This was fixed by doing `pip3 install --user logbook`.

**Comment by hongquan** [comment]
Thanks, @goodevilgenius , for reporting. I've just release the fix: https://github.com/hongquan/CurliPie/releases/tag/v0.7.3
